import shirt from '../assets/shirt.png'

export const mainproductsdata = [
    {
        id: 1,
        proName: "Denim Shirt for Bisexual",
        proDesc: "This is a versatile denim shirt suitable for both men and women. dhdh dhd dhdhd dhdh dhdd dhd",
        proPrice: "1000",
        proImage: shirt.src,
        proRating: 4.8,
    },
    {
        id: 2,
        proName: "Unisex Hoodie",
        proDesc: "A comfortable and stylish hoodie perfect for everyone.",
        proPrice: "1200",
        proImage: shirt.src,
        proRating: 1,
    },
    {
        id: 3,
        proName: "Leather Jacket",
        proDesc: "A classic leather jacket that adds an edge to any outfit.",
        proPrice: "3500",
        proImage: shirt.src,
        proRating: 4.7,
    },
    {
        id: 4,
        proName: "Casual Sneakers",
        proDesc: "Stylish and comfortable sneakers for everyday wear.",
        proPrice: "800",
        proImage: shirt.src,
        proRating: 2.2,
    },
    {
        id: 5,
        proName: "Elegant Watch",
        proDesc: "A sleek and elegant watch to complete your look.",
        proPrice: "1500",
        proImage: shirt.src,
        proRating: 3.5,
    }
];


export const cities = [
    "Ariyalur",
    "Chengalpattu",
    "Chennai",
    "Coimbatore",
    "Cuddalore",
    "Dharmapuri",
    "Dindigul",
    "Erode",
    "Kallakurichi",
    "Kanchipuram",
    "Kanyakumari",
    "Karur",
    "Krishnagiri",
    "Madurai",
    "Nagapattinam",
    "Namakkal",
    "Nilgiris",
    "Perambalur",
    "Pudukkottai",
    "Ramanathapuram",
    "Ranipet",
    "Salem",
    "Sivaganga",
    "Tenkasi",
    "Thanjavur",
    "Theni",
    "Thoothukudi",
    "Tiruchirappalli",
    "Tirunelveli",
    "Tirupathur",
    "Tiruppur",
    "Tiruvallur",
    "Tiruvannamalai",
    "Tiruvarur",
    "Vellore",
    "Viluppuram",
    "Virudhunagar"
];

export const states = [
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal"
  ];
  
