import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";
import Navbar from "./_components/Navbar";
import Footer from "./_components/Footer";

const inter = Inter({ subsets: ["latin"] });

const myfont = localFont({
  src: [
    {
      path: "../../public/fonts/fonnts.com-Regulator_Nova_Bold.otf",
      // weight: "200"
    }
  ],
})

export const metadata: Metadata = {
  title: "E-Commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} >
        <div className="w-full realative">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
