import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";
import Navbar from "./_components/Navbar";
import dynamic from "next/dynamic";
import { Toaster } from 'sonner'
import RegisterModel from "./_components/RegisterModal";
import LoginModel from "./_components/LoginModel";
import { SessionProvider } from 'next-auth/react'
import { auth } from "../../auth";
const Footer = dynamic(() => import('./_components/Footer'))

const inter = Inter({ subsets: ["latin"] });

const myfont = localFont({
  src: [
    {
      path: "../../public/fonts/fonnts.com-Regulator_Nova_Bold.otf",
      // weight: "200"
    }
  ],
})

export const metadata: Metadata = {
  title: "E-Commerce",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth()
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={inter.className} >
          <div className="w-full realative">
            <Navbar />
            <Toaster position="bottom-right" expand={false} richColors />
            <RegisterModel />
            <LoginModel />
            {children}
            {/* <Footer /> */}
          </div>
        </body>
      </html>
    </SessionProvider>
  );
}
