import type { Metadata } from "next";
import { SessionProvider } from 'next-auth/react';
import { Inter } from "next/font/google";
import { Toaster } from 'sonner';
import { auth } from "../../auth";
import LoginModel from "./_components/LoginModel";
import Navbar from "./_components/Navbar";
import RegisterModel from "./_components/RegisterModal";
import "./globals.css";

export const metadata: Metadata = {
  title: "E-Commerce",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth()
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body style={{ fontFamily: 'Conthrax' }} >
          <div className="w-full realative">
            <Navbar />
            <Toaster position="bottom-right" expand={false} richColors />
            <RegisterModel />
            <LoginModel />
            {children}
          </div>
        </body>
      </html>
    </SessionProvider>
  );
}
